service:
  name: bbe-bot-sls

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TELEGRAM_TOKEN: ${ssm:/bbe-telegram-token~true}
    TELEGRAM_ADMIN_ID: ${ssm:/bbe-telegram-adminId~true}

functions:
  versionCheck:
    handler: src/handlers/utils.versionCheck
    events:
      - schedule:
          rate: cron(0 12 * * *)
